-- MySQL Script generated by MySQL Workbench
-- Sun Mar  6 18:46:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Baza` DEFAULT CHARACTER SET utf8 ;
USE `Baza` ;

-- -----------------------------------------------------
-- Table `Baza`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Baza`.`Korisnik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Korisnicko Ime` VARCHAR(256) NOT NULL,
  `Ime` VARCHAR(256) NOT NULL,
  `Sifra` VARCHAR(512) NOT NULL,
  `Email` VARCHAR(256) NOT NULL,
  `Telefon` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
insert into Korisnik values(1,'admin','admin','admin','admin@admin.com','123456789');